packages:
  - "apps/*"
  - "packages/*"
  - "apps/examples/*"
  - "packages/examples/*"
  - "apps/examples/nextjs/*"
  - "apps/examples/nestjs/*"
  - "apps/examples/ruby-on-rails/*"
  - "apps/examples/scala/*"
  - "apps/examples/react/*"
  - "apps/examples/python/*"
  - "apps/examples/java/*"
