services:
  db:
    image: mysql:8.0.37-bookworm
    container_name: mysql-latest-container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssword1234!
      - MYSQL_DATABASE=nrdStarterAppDatabase
    volumes:
    - ../../db/mysql:/var/lib/mysql 
  web:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    ports:
      - "3010:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=P@ssword1234!