networks:
  backend-network:
    driver: bridge
services:
  mongo:
    image: mongo:latest
    container_name: mongo-latest-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ../../db/mongo:/data/db
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet"]
      interval: 10s
      retries: 5
      start_period: 5s