services:
  db:
    image: mongo:latest
    container_name: mongo-latest-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=P@ssword1234!
      - MONGO_INITDB_DATABASE=nrdStarterAppDatabase
    volumes:
      - ./mongo_data:/data/db
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'db.runCommand(\"ping\").ok' | mongo --host mongo:27017/test --quiet"]
      interval: 10s
      retries: 5
      start_period: 30s

  web:
    image: mongo-express:latest
    container_name: mongo-express-container
    ports:
      - "3011:8081"
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=P@ssword1234!
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      db:
        condition: service_healthy